name: legal-sky-ai
description: Complete Legal RAG Assistant with Voice Support (9 Indian Languages)
compute:
  spec:
    kind: serverless
env:
- name: SARVAM_API_KEY
  value: sk_sn9w8roe_QwQ3Sc7Xa9acvNvTh5iV8Iek
command:
- uvicorn
- app:app
- --host
- 0.0.0.0
- --port
- '8000'
port: 8000
resources:
  memory: 4Gi
  cpu: '2'
